import { Matrix } from '../contracts';

const getMatrices = async () => {
    const matrices: Matrix[] = [
        {
            id: '1',
            Commodity: 'Commodity 1',
            SupplierName: 1,
            StateName: 'StateName 1',
            LDCNAME: 'LDCNAME 1',
            CustomerType: 'CustomerType 1',
            Zone: 'Zone 1',
            LoadZone: 1,
            LoadFactorFrom: 'LoadFactorFrom 1',
            LoadFactorUpTo: 'LoadFactorUpTo 1',
            DemandRangeFrom: 'DemandRangeFrom 1',
            DemandRangeUpTo: 'DemandRangeUpTo 1',
            Congestion: 'Congestion 1',
            GRT: 'GRT 1',
        },
        {
            id: '2',
            Commodity: 'Commodity 2',
            SupplierName: 2,
            StateName: 'StateName 2',
            LDCNAME: 'LDCNAME 2',
            CustomerType: 'CustomerType 2',
            Zone: 'Zone 2',
            LoadZone: 2,
            LoadFactorFrom: 'LoadFactorFrom 2',
            LoadFactorUpTo: 'LoadFactorUpTo 2',
            DemandRangeFrom: 'DemandRangeFrom 2',
            DemandRangeUpTo: 'DemandRangeUpTo 2',
            Congestion: 'Congestion 2',
            GRT: 'GRT 2',
        },
        {
            id: '3',
            Commodity: 'Commodity 3',
            SupplierName: 3,
            StateName: 'StateName 3',
            LDCNAME: 'LDCNAME 3',
            CustomerType: 'CustomerType 3',
            Zone: 'Zone 3',
            LoadZone: 3,
            LoadFactorFrom: 'LoadFactorFrom 3',
            LoadFactorUpTo: 'LoadFactorUpTo 3',
            DemandRangeFrom: 'DemandRangeFrom 3',
            DemandRangeUpTo: 'DemandRangeUpTo 3',
            Congestion: 'Congestion 3',
            GRT: 'GRT 3',
        },
        {
            id: '4',
            Commodity: 'Commodity 4',
            SupplierName: 4,
            StateName: 'StateName 4',
            LDCNAME: 'LDCNAME 4',
            CustomerType: 'CustomerType 4',
            Zone: 'Zone 4',
            LoadZone: 4,
            LoadFactorFrom: 'LoadFactorFrom 4',
            LoadFactorUpTo: 'LoadFactorUpTo 4',
            DemandRangeFrom: 'DemandRangeFrom 4',
            DemandRangeUpTo: 'DemandRangeUpTo 4',
            Congestion: 'Congestion 4',
            GRT: 'GRT 4',
        },
        {
            id: '5',
            Commodity: 'Commodity 5',
            SupplierName: 5,
            StateName: 'StateName 5',
            LDCNAME: 'LDCNAME 5',
            CustomerType: 'CustomerType 5',
            Zone: 'Zone 5',
            LoadZone: 5,
            LoadFactorFrom: 'LoadFactorFrom 5',
            LoadFactorUpTo: 'LoadFactorUpTo 5',
            DemandRangeFrom: 'DemandRangeFrom 5',
            DemandRangeUpTo: 'DemandRangeUpTo 5',
            Congestion: 'Congestion 5',
            GRT: 'GRT 5',
        },
    ];

    return matrices;
};

export const MatricesService = {
    getMatrices,
};
